version: '3'
networks:
  sound_network:
    driver: bridge
services:

  client:
    env_file: .env
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./client:/code
      - /code/node_modules
    networks:
      - sound_network
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    # expose:
    #   - "${CLIENT_PORT}"
    command: sh -c "npm run dev"

  server:
    env_file: .env
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./server:/code
      - /code/node_modules
    networks:
      sound_network:
        aliases:
          - ${HOST_ALIAS}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    # expose:
    #   - "${SERVER_PORT}"
    environment:
      WAIT_HOSTS: mongodb:${MONGO_PORT}
    command: sh -c "export GOOGLE_APPLICATION_CREDENTIALS=google-storage-auth.json; npm run dev"
    # depends_on:
    #   - mongodb
    # command: sh -c "/wait && npm run dev"
  
  # mongodb:
  #   hostname: mongodb
  #   env_file: .env
  #   image: mongo
  #   restart: always
  #   networks:
  #     - sound_network
  #   logging:
  #     driver: none
  #   ports:
  #     - ${MONGO_PORT}:${MONGO_PORT}
