version: '3'
networks:
  cancer_network:
    driver: bridge
services:

  web-app:
    env_file: .env
    build:
      context: ./web-app
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./web-app:/code
      # - /code/node_modules
    networks:
      - cancer_network
    ports:
      - "${WEB_APP_PORT}:${WEB_APP_PORT}"
    command: sh -c "npm run dev"

  api:
    env_file: .env
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./api:/code
      # - /code/node_modules
    networks:
      cancer_network:
        aliases:
          - ${HOST_ALIAS}
    ports:
      - "${API_PORT}:${API_PORT}"
    command: sh -c "npm run dev"
  