version: '3'
networks:
  cancer_network:
    driver: bridge
services:

  client:
    env_file: .env
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./client:/code
      # - /code/node_modules
    networks:
      - cancer_network
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    command: sh -c "npm run dev"

  server:
    env_file: .env
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./server:/code
      # - /code/node_modules
    networks:
      cancer_network:
        aliases:
          - ${HOST_ALIAS}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: sh -c "npm run dev"
  