FROM nikolaik/python-nodejs:python3.7-nodejs13

WORKDIR /code
COPY . /code

# ---------------------------------
# - UNCOMMENT IF LOCAL MONGO USED -
# ---------------------------------
# Wait until db is ready
# ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.0/wait /wait
# RUN chmod +x /wait
