FROM nikolaik/python-nodejs:python3.7-nodejs13

COPY . /code
COPY package*.json /code/

# Install packages
WORKDIR /code
# RUN npm install

# BETTER DOCKER SETUP
# https://stackoverflow.com/questions/51097652/install-node-modules-inside-docker-container-and-synchronize-them-with-host

# ---------------------------------
# - UNCOMMENT IF LOCAL MONGO USED -
# ---------------------------------
# Wait until db is ready
# ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.0/wait /wait
# RUN chmod +x /wait
